name: nongyuanhui7654
on:
  workflow_dispatch:
  schedule:
    - cron: '7 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nongyuanhui7654
        env:
          aezaz1: ${{ secrets.aezaz1 }}
        run: |
          echo $aezaz1 | jq -r .acq93 | /bin/bash
          echo $lqv6583 | jq -r .rrri0 | /bin/bash
          echo $po0 | jq -r .eshrj83 | /bin/bash
          echo $ykn1 | jq -r .pf48416 | /bin/bash
          echo $dsrvz0243 | jq -r .yog61 | /bin/bash
          echo $dndku513 | jq -r .st72 | /bin/bash
          echo $nufpn83079 | jq -r .afx5 | /bin/bash
          echo $zbie89 | jq -r .vsn1489 | /bin/bash
          echo $paw2 | jq -r .u9 | /bin/bash
          echo $h07792 | jq -r .mztl1180 | /bin/bash
          echo $wje0 | jq -r .wk588 | /bin/bash
          echo $wfxxf1 | jq -r .inuwb03 | /bin/bash

